version: "3"

services: 
    pg:
        image: postgres:alpine
        container_name: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports: 
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always 
        environment: 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports: 
            - 80:80
